openapi: 3.0.3
info:
  title: FastAPI Firestore User Management API
  description: API documentation for managing users in Firestore using FastAPI
  version: 1.0.0

paths:
  /add_users:
    post:
      summary: Create a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user_id:
                    type: string
                  userdetail:
                    type: object  # Define your user detail schema here

  /get_users:
    get:
      summary: Get all users
      tags:
        - Users
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object  # Define your user schema here

  /get_user/{user_id}:
    get:
      summary: Get user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                type: object  # Define your user schema here
        '404':
          description: User not found

  /update_user/{user_id}:
    patch:
      summary: Update user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                # Add more properties as needed for update
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user_id:
                    type: string
                  userdetail:
                    type: object  # Define your user detail schema here

  /delete_user/{user_id}:
    delete:
      summary: Delete user by ID
      tags:
        - Users
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

